### ISSUE TITLE
New "data" at every check

### ISSUE THREAD

**Issue by pfay-fc** [tigger0jk/SKAdNetworkIdentifiers#1]
It seems like the data from unity is in a different order every time it's pulled. If they're not going to give us a consistent order we may need to parse and sort the data before saving it so the diffs are actually useful and relevant.

**Comment by tigger0jk** [comment]
Sorting json with d25cf6902433038af32865f0031a8959303e0561 and xml with 00cbd5ca58aa8f90036ff90fd2d91d3a41a98dd4 - this does tie us to the current xml structure, but so be it
